name: Deploy to DreamHost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DreamHost
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DREAMHOST_HOST }}
          username: ${{ secrets.DREAMHOST_USER }}
          key: ${{ secrets.DREAMHOST_SSH_KEY }}
          script: |
            /home/dh_eprtrd/deploy-klub-kornel.sh
